#############################################################################
# GitHub Action to Update github.io
#
#############################################################################
name: "R: Update github.io"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target Version without (-SNAPSHOT)'
        required: true
jobs:
  update:
    name: update github.io ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Shell Script
        run: |
          ./.ci/update-github-io.sh ${{ github.event.inputs.version }}
